[functions.stripe-webhook]
verify_jwt = false
[functions.create-portal-link]
enabled = true
verify_jwt = true
import_map = "./functions/create-portal-link/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-portal-link/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-portal-link/*.html" ]

[functions.check-pro-status]
enabled = true
verify_jwt = true
import_map = "./functions/check-pro-status/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-pro-status/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-pro-status/*.html" ]
